In [1]:
import numpy as np
import pandas as pd

In [4]:
a = [1,2,3]
b = np.array(a)
b

array([1, 2, 3])

In [5]:
type(b)

numpy.ndarray

In [6]:
c = np.array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
c[1,:]

array([4, 5, 6])

In [10]:
d = np.zeros((4,3))
d

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
e = np.ones((4,3))
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
f = np.random.rand(4,3)
f

array([[0.02840348, 0.53247651, 0.84835181],
       [0.49123574, 0.50471746, 0.43418611],
       [0.18508464, 0.60670031, 0.52375606],
       [0.96316227, 0.55642715, 0.80501398]])

In [15]:
x = np.linspace(1,10,10)
x

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [16]:
y = x**2
y

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [18]:
z = np.sqrt(y)
z

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
df = pd.DataFrame({'x':x,'y':y,'z':z})
df

x      y     z
0   1.0    1.0   1.0
1   2.0    4.0   2.0
2   3.0    9.0   3.0
3   4.0   16.0   4.0
4   5.0   25.0   5.0
5   6.0   36.0   6.0
6   7.0   49.0   7.0
7   8.0   64.0   8.0
8   9.0   81.0   9.0
9  10.0  100.0  10.0